site :opscode

cookbook 'apt'
cookbook 'sudo'
cookbook 'timezone'
cookbook 'build-essential'
cookbook 'openssl'
cookbook 'readline'
cookbook 'curl'
cookbook 'git'
cookbook 'zsh'
cookbook 'tmux'
cookbook 'vim'
cookbook 'mysql'
cookbook 'cmake'
cookbook 'ruby_build', github: 'fnichol/chef-ruby_build'
cookbook 'rbenv', github: 'fnichol/chef-rbenv'
cookbook 'python'
cookbook 'google-chrome'
