source 'https://api.berkshelf.com'

cookbook 'apt'
cookbook 'ark'
cookbook 'sudo'
cookbook 'timezone'
cookbook 'build-essential'
cookbook 'openssl'
cookbook 'readline'
cookbook 'curl'
cookbook 'git'
cookbook 'zsh'
cookbook 'tmux'
cookbook 'vim'
cookbook 'mysql'
cookbook 'npm'
cookbook 'rbenv', github: 'calorie/chef-rbenv', branch: 'patch-1'
cookbook 'python'
cookbook 'google-chrome'
cookbook 'ubuntu-change-source-list', github: 'ywjno/ubuntu-change-source-list'
cookbook 'locale'
cookbook 'docker'
cookbook 'golang'
